plugins {
    id 'fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
}

group = 'net.mat0u5.lifeseries.addons'
version = project.addon_version
base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Required only for compilation. Override with -Plifeseries_jar=/path/to/lifeseries.jar
    modCompileOnly files(project.lifeseries_jar)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand(version: project.version)
    }
}
