# https://fabricmc.net/develop
# https://www.curseforge.com/minecraft/mc-mods/carpet
# https://modrinth.com/plugin/simple-voice-chat

minecraft_version=1.21.11
fabric_version=0.140.2+1.21.11
target_version=>=1.21.11
min_version=1.21.11
max_version=1.21.11

carpet_mod_version=7367605
voicechat_mod_version=1.21.11-2.6.10
